 - name: Release
      uses: qcastel/github-actions-maven-release@master
      with:
        release-branch-name: "master"

        git-release-bot-name: "release-bot"
        git-release-bot-email: "release-bot@example.com"

        access-token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
